### ISSUE TITLE
Multiple selectors; title and href of links by css class?

### ISSUE THREAD

**Issue by Daaniiieel** [marcomontalbano/html-miner#11]
Hey, @marcomontalbano 
On one of the other issues, you suggested this to another user.: 

> 
> htmlMiner(html, {
>   _each_: 'a',
>   text: function(arg) {
>     return arg.$scope.text();
>   },
>   href: function(arg) {
>     return arg.$scope.attr('href');
>   }
> })

I want to do it a bit differently. I am scraping a news website and would like to

- **select an element by a css selector (example .highlight--frontpage-title)**
- **get it's text**
- **get it's href**

Can you help me please?
TY!
**P.S.:** The documentation of this project could use a bit of improvements. Once I fully understand it, might commit.

**Comment by marcomontalbano** [comment]
Hi @Daaniiieel,
in the example you copied/pasted there's a typo. The `each` keyword should be `_each_`.
If I understood well, you should have an HTML like this:
```html
<div>
  <a class="highlight--frontpage-title" href="https://example.com/1">link 1</a>
  <a class="highlight--frontpage-title" href="https://example.com/2">link 2</a>
  <a class="highlight--frontpage-title" href="https://example.com/3">link 3</a>
  <a class="highlight--frontpage-title" href="https://example.com/4">link 4</a>
</div>
```
To mine the data that you want, you can use this selector:
```js
{
  _each_: '.highlight--frontpage-title',
  text: function(arg) {
    return arg.$scope.text();
  },
  href: function(arg) {
    return arg.$scope.attr('href');
  }
}
```
Let me know if this solve your question.

Regarding the documentation, PR are more than welcome!
Maybe I can add more use cases to the readme.

**Comment by Daaniiieel** [comment]
Thank you!
