### ISSUE TITLE
text only? img and a tags not supported?

### ISSUE THREAD

**Issue by mark134340** [marcomontalbano/html-miner#8]

**Comment by marcomontalbano** [comment]
Hi, the question is not so clear but I try to give you an answer.

You can fetch only the text by providing just a selector.

```js
htmlMiner(html, '.title');
```

In this way you are getting the `.text()` from the element. This means that if you provide an `img` as selector you will get an empty string.

---

You can get the image `src` using a function. 

```js
htmlMiner(html, function(arg) {
  return arg.$('img').attr('src')
})
```

Or you can get all `src` from all images as array

```js
htmlMiner(html, function(arg) {
  return Array.from(arg.$('img')).map(function(img) {
    return arg.$(img).attr('src')
  })
})
```

---

You can do the same with an `a` tag.

```js
htmlMiner(html, function(arg) {
  return arg.$('a').attr('href')
})
```

If you need to fetch more information from selectors you can simply use an object like this:

```js
htmlMiner(html, {
  _each_: 'a',
  text: function(arg) {
    return arg.$scope.text();
  },
  href: function(arg) {
    return arg.$scope.attr('href');
  }
})
```

Let me know if this respond to you question so I can close the issue
